Added DeleteQuery
squigglesql/squigglesql pull request #15
Opened 2021-05-25 04:16 UTC by codyebberson

Added `DeleteQuery` to delete rows.

The structure follows `UpdateQuery` except without the update values.

MySQL has unique syntax when using table aliases:
* MySQL:  `DELETE e FROM employees e`
* Postgres: `DELETE FROM employees e`

Hence the addition of `AbstractSqlSyntax.compileDeleteFrom`

2021-05-25 17:15 UTC, enepomnyaschih requested changes
Thank you for a contribution!

* Please add JDBC (non-mock) tests for deletion queries involving two or more database tables for 3 supported database engines (e.g. by using TestUtils.withDatabase). I am not sure that all implementations are correct. In fact, I think that H2 doesn't support this feature at all - if that's true, please add a method to TestDatabase class to suppress this test case and, ideally, please provide a user-friendly error message.
* Please mention the new feature in README.md and CHANGELOG.md.
* I'll publish this as version 4.2.0 once merged, so please also update pom.xml.

2021-05-25 17:15 UTC, enepomnyaschih commented on src/main/java/com/github/squigglesql/squigglesql/query/DeleteQuery.java
> + * Copyright 2019 Egor Nepomnyaschih.
Please update the copyright clauses for new files to:

    Copyright 2021 <Your Name>

2021-05-25 17:15 UTC, enepomnyaschih commented on src/main/java/com/github/squigglesql/squigglesql/query/DeleteQuery.java
> + */
Please add `@since 4.2.0` for all new classes.

2021-05-25 17:15 UTC, enepomnyaschih commented on src/main/java/com/github/squigglesql/squigglesql/syntax/AbstractSqlSyntax.java
> +     * @since 4.1.0
```suggestion
     * @since 4.2.0
```

2021-05-25 19:00 UTC, codyebberson commented
@enepomnyaschih Thank you for taking the time to review.  I submitted changes to address your feedback.

> * Please add JDBC (non-mock) tests for deletion queries involving two or more database tables for 3 supported database engines (e.g. by using TestUtils.withDatabase). I am not sure that all implementations are correct. In fact, I think that H2 doesn't support this feature at all - if that's true, please add a method to TestDatabase class to suppress this test case and, ideally, please provide a user-friendly error message.

You were right.  I decided to remove the multiple table functionality completely, and show a error message if multiple tables are referenced.

> * Please mention the new feature in README.md and CHANGELOG.md.

I added to CHANGELOG.md.  I did not see an obvious place in the README.md.

> * I'll publish this as version 4.2.0 once merged, so please also update pom.xml.

Great!  Thank you for this library!  Please let me know if there are any follow-up issues.

2021-05-26 18:28 UTC, enepomnyaschih approved these changes

2021-05-26 18:39 UTC, merged

2021-05-26 18:53 UTC, enepomnyaschih commented
I've published the new version - it should show up in Maven Central soon.